# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: uea-stemmer 0.10.2 ruby lib

Gem::Specification.new do |s|
  s.name = "uea-stemmer"
  s.version = "0.10.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Marie-Claire Jenkins", "Dan J. Smith", "Richard Churchill", "Jason Adams"]
  s.date = "2017-08-14"
  s.description = "Port of UEA-Lite Stemmer to Ruby, a conservative stemmer for search and indexing."
  s.email = "jasonmadams@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/uea-stemmer.rb",
    "lib/uea-stemmer/rule.rb",
    "lib/uea-stemmer/string_helpers.rb",
    "lib/uea-stemmer/word.rb",
    "test/test_helper.rb",
    "test/uea_stemmer_test.rb",
    "uea-stemmer.gemspec"
  ]
  s.homepage = "http://github.com/ealdent/uea-stemmer"
  s.rubygems_version = "2.4.8"
  s.summary = "Port of UEA-Lite Stemmer to Ruby, a conservative stemmer for search and indexing."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<uea-stemmer>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<uea-stemmer>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<uea-stemmer>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

